package examensarbete.model.test;

public enum MatchType {
	MATCH,
	LOCATION_CHANGED_MATCH,
	NO_MATCH,
	COLOR_CHANGED_MATCH,
	TEXT_CHANGED_MATCH,
	LABEL_CHANGED_MATCH,
	WEB_CHANGED_MATCH, 
	TEXTSTYLE_CHANGED_MATCH
}
